# Generated by Django 6.0.1 on 2026-02-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ms', models.BigIntegerField(db_index=True)),
                ('timestamp_et', models.DateTimeField()),
                ('time_till_end', models.CharField(max_length=10)),
                ('seconds_till_end', models.IntegerField(db_index=True)),
                ('oracle_btc_price', models.FloatField(blank=True, null=True)),
                ('binance_btc_price', models.FloatField(blank=True, null=True)),
                ('lag', models.FloatField(blank=True, null=True)),
                ('binance_ret1s_x100', models.FloatField(blank=True, null=True)),
                ('binance_ret5s_x100', models.FloatField(blank=True, null=True)),
                ('binance_volume_1s', models.FloatField(blank=True, null=True)),
                ('binance_volume_5s', models.FloatField(blank=True, null=True)),
                ('binance_volma_30s', models.FloatField(blank=True, null=True)),
                ('binance_volume_spike', models.FloatField(blank=True, null=True)),
                ('binance_atr_5s', models.FloatField(blank=True, null=True)),
                ('binance_atr_30s', models.FloatField(blank=True, null=True)),
                ('binance_rvol_30s', models.FloatField(blank=True, null=True)),
                ('binance_vwap_30s', models.FloatField(blank=True, null=True)),
                ('binance_p_vwap_5s', models.FloatField(blank=True, null=True)),
                ('binance_p_vwap_30s', models.FloatField(blank=True, null=True)),
                ('lat_dir_raw_x1000', models.FloatField(blank=True, null=True)),
                ('lat_dir_norm_x1000', models.FloatField(blank=True, null=True)),
                ('up_bids', models.JSONField(default=list)),
                ('up_asks', models.JSONField(default=list)),
                ('down_bids', models.JSONField(default=list)),
                ('down_asks', models.JSONField(default=list)),
                ('pm_up_bid_depth5', models.FloatField(blank=True, null=True)),
                ('pm_up_ask_depth5', models.FloatField(blank=True, null=True)),
                ('pm_up_total_depth5', models.FloatField(blank=True, null=True)),
                ('pm_down_bid_depth5', models.FloatField(blank=True, null=True)),
                ('pm_down_ask_depth5', models.FloatField(blank=True, null=True)),
                ('pm_down_total_depth5', models.FloatField(blank=True, null=True)),
                ('pm_up_spread', models.FloatField(blank=True, null=True)),
                ('pm_down_spread', models.FloatField(blank=True, null=True)),
                ('pm_up_imbalance', models.FloatField(blank=True, null=True)),
                ('pm_down_imbalance', models.FloatField(blank=True, null=True)),
                ('pm_up_microprice', models.FloatField(blank=True, null=True)),
                ('pm_down_microprice', models.FloatField(blank=True, null=True)),
                ('pm_up_bid_slope', models.FloatField(blank=True, null=True)),
                ('pm_up_ask_slope', models.FloatField(blank=True, null=True)),
                ('pm_down_bid_slope', models.FloatField(blank=True, null=True)),
                ('pm_down_ask_slope', models.FloatField(blank=True, null=True)),
                ('pm_up_bid_eatflow', models.FloatField(blank=True, null=True)),
                ('pm_up_ask_eatflow', models.FloatField(blank=True, null=True)),
                ('pm_down_bid_eatflow', models.FloatField(blank=True, null=True)),
                ('pm_down_ask_eatflow', models.FloatField(blank=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='market.market')),
            ],
            options={
                'ordering': ['timestamp_ms'],
                'indexes': [models.Index(fields=['market', 'timestamp_ms'], name='market_mark_market__06ea7b_idx'), models.Index(fields=['market', 'seconds_till_end'], name='market_mark_market__4ec895_idx')],
            },
        ),
    ]
