# Generated by Django 6.0.1 on 2026-02-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='market',
            name='status',
            field=models.CharField(choices=[('analyzed', 'Analyzed'), ('not_analyzed', 'Not Analyzed')], default='not_analyzed', max_length=20),
        ),
    ]
